spring:
  profiles:
    active: local  # 기본값으로 local 설정
    group:
      local: local
      blue: blue,common,secret
      green: green,common,secret

server:
  env: local # 기본값으로 local 설정

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        auto_quote_keyword: true
  datasource:
    url: jdbc:mysql://localhost:3305/moaguide?serverTimezone=UTC
    username: moaguide
    password: whrkrxnwkahdkrkdlem
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
      coolsms:
        apiKey: ${COOLSMS_API_KEY:NCS6DIOVFX0WIBEE}
        apiSecret: ${COOLSMS_API_SECRET:4DWOYEGVJ3MPVSE8ZRWQYCG4ZSD9Y1MY}
        senderNumber: ${COOLSMS_SENDER_NUMBER:01022476408}
  jwt:
    secret: 3sGuraC8zLS9wkbN2QWtygvXV5JHjqM6DeP4ERTBZYnmfFcAdK

server:
  port: 8080
y
serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
  data:
    redis:
      host: localhost
      port: 6379



server:
  port: 8080

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

serverName: green_server

---

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        auto_quote_keyword: true
  open-in-view: false  # 중요: Hibernate의 Open Session In View를 비활성화합니다.
  jwt:
    secret: 3sGuraC8zLS9wkbN2QWtygvXV5JHjqM6DeP4ERTBZYnmfFcAdK
  jackson:
    time-zone: Asia/Seoul
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssang2247@moaguide.com
    password: ocjumyhnocmgdnhv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: DEBUG
    org:
      hibernate:
        SQL:
          DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    session:
      timeout: 3600
  timezone: Asia/Seoul